---     
apiVersion: v1
kind: Service
metadata:
  name: firstdemoapp
  labels:
    app: firstdemoapp
spec:
  type: NodePort
  selector:
    app: firstdemoapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8086
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdemoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstdemoapp
  template:
    metadata:
      labels:
        app: firstdemoapp
    spec:
      containers:
      - name: firstdemoapp
        image: webshweta/firstdemoapp:latest
        ports:
          - containerPort: 8086
        livenessProbe:
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 30
          timeoutSeconds: 1