apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/shwetakangane/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 04 Jun 2024 13:00:42 IST
        provider: minikube.sigs.k8s.io
        version: v1.33.1
      name: cluster_info
    server: https://127.0.0.1:56065
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 04 Jun 2024 13:00:42 IST
        provider: minikube.sigs.k8s.io
        version: v1.33.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/shwetakangane/.minikube/profiles/minikube/client.crt
    client-key: /Users/shwetakangane/.minikube/profiles/minikube/client.key